<?php


/**
 *Implementation hook_block_info()
 **/
function juanrueda_contador_block_info() {
  $blocks = array();

  $blocks['contador_personalizado'] = array(
    'info' => t('Contador personalizado'),
    );

   return $blocks;
}

/**
 *Implementation hook_block_view()
 **/
function juanrueda_contador_block_view($delta = '') {
  $blocks = array();

  switch ($delta) {
    case 'contador_personalizado':
      $blocks['content'] = html_contador_personalizado();
      break;
  }

  return $blocks;

}

/**
 * Implements hook_field_extra_fields().
 */
function juanrueda_contador_field_extra_fields() {

  $extra['node']['contador'] = array(
  'display' => array(
    'node_contador' => array(
      'label' => t('Contador general'),
      'weight' => -4,
    ),
  )
  );

  return $extra;

}


/**
 * Implements hook_node_view().
 */
function juanrueda_contador_node_view($node, $view_mode, $langcode) {
  // $node->content['node_contador'][0]['#markup'] = html_contador_personalizado($node);
  $node->content['node_contador'][0]['#markup'] = 'Prueba';
}

function html_contador_personalizado($node = NULL) {
  dpm($node);
}

function _contador_comentarios($nid) {

  $db = db_select('comment', 'c')
    ->fields('c', array('nid'));
  $db->addExpression('count(c.nid)', 'total');
  $db->condition('nid', $nid);
  $result = $db->execute();
  $record = $result->fetchAssoc();

  return $record['total'];

}
