<?php

/**
 * Implements hook_field_formatter_info()
 */
function juanrueda_galeria_field_formatter_info() {
	return array(
      'galeria_elastislide' => array(
        'label' => t('Galeria elastislide'),
        'field types' => array('entityreference'),
        'settings' => array(
          'view_mode' => '',
          'links' => TRUE,
        ),
      ),
    );
}


/**
 * Implements hook_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display);
 */
function juanrueda_galeria_hook_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  switch ($display['type']) {
    case 'galeria_elastislide':
      if (!empty($items)) {
        foreach ($items as $delta => $item) {
          $element[$delta] = array(
            '#markup' =>   'Prueba',
            );
        }
      }
    break;
  }
}

/**
 * Implements hook_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state)
 */
function juanrueda_galeria_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $element = array();
  dpm($display);

  if ($display['type'] == 'galeria_elastislide') {
    $element['galeria_elastislide'] = array(
      '#title' => t('Cantidad imagenes'),
      '#type' => 'textfield',
      '#size' => 20,
      '#default_value' => $settings['galeria_elastislide'],
      '#required' => TRUE,
    );
  }

  return $element;

}


/**
 * Implements hook_field_formatter_settings_summary().
 */
function juanrueda_galeria_field_formatter_settings_summary($field, $instance, $view_mode) {
  if ($display['type'] == 'galeria_elastislide') {
    $summary[] = $settings['galeria_elastislide'] ? t('Link to the referenced entity') : t('No link');
  }

  return implode('<br />', $summary);

}

