<?php

/**
 * Implements hook_field_formatter_info()
 */
function juanrueda_galeria_field_formatter_info() {
	return array(
      'galeria_elastislide' => array(
        'label' => t('Galeria elastislide'),
        'field types' => array('entityreference'),
      ),
    );
}


/**
 * Implements hook_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display);
 */
function juanrueda_galeria_hook_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  switch ($display['type']) {
    case 'galeria_elastislide':
      if (!empty($items)) {
        foreach ($items as $delta => $item) {
          $element[$delta] = array(
            '#markup' =>   'Prueba',
            );
        }
      }
    break;
  }
}
