<?php

/**
 * Implements hook_field_formatter_info()
 */
function juanrueda_galeria_field_formatter_info() {
	return array(
      'galeria_elastislide' => array(
        'label' => t('Galeria elastislide'),
        'field types' => array('entityreference'),
        'settings' => array(
          'view_mode' => '',
          'links' => TRUE,
          'image_style' => '',
        ),

      ),
    );
}


/**
 * Implements hook_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state)
 */
function juanrueda_galeria_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $image_styles = image_style_options(FALSE);


  $element = array();

  if ($display['type'] == 'galeria_elastislide') {
    $element['view_mode'] = array(
      '#title' => t('Cantidad imagenes'),
      '#type' => 'textfield',
      '#size' => 20,
      '#default_value' => $settings['view_mode'] ? $settings['view_mode'] : 5,
      '#required' => TRUE,
    );

    $element['image_style'] = array(
      '#title' => t('Image style'),
      '#type' => 'select',
      '#default_value' => $settings['image_style'],
      '#empty_option' => t('None (original image)'),
      '#options' => $image_styles,
    );
  }

  return $element;

}


/**
 * Implements hook_field_formatter_settings_summary().
 */
function juanrueda_galeria_field_formatter_settings_summary($field, $instance, $view_mode) {

  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];

  $image_styles = image_style_options(FALSE);

  $summary = array();

  if ($display['type'] == 'galeria_elastislide') {
    $summary[] = $settings['view_mode'] ? t('Candidad seleccionada') : t('Esta por defecto');

    if (isset($image_styles[$settings['image_style']])) {
      $summary[] = t('Image style: @style', array('@style' => $image_styles[$settings['image_style']]));
    }
    else {
      $summary[] = t('Original image');
    }
  }

  return implode('<br />', $summary);

}


/**
 * Implements hook_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display);
 */
function juanrueda_galeria_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {

  switch ($display['type']) {
    case 'galeria_elastislide':
      if (!empty($items)) {
        dpm($items);
        foreach ($items as $delta => $item) {
          $element[$delta] = array(
            '#markup' =>  _view_galeria_eslasticslider($item['target_id']) ,
            );
        }

      }
    break;
  }

  return $element;
}

function _view_galeria_eslasticslider($nid) {
  $node = &drupal_static(__FUNCTION__);

  drupal_add_library('juanrueda_libraries', 'elastislide');
  $node = node_load($nid);
  return render(field_view_field('node', $node, 'field_imagen_galeria', array('settings' => array('image_style' => 'original'))));
  dpm($node);

}
