<?php

function juanrueda_libraries_library() {

  $libraries['elastislide'] = array(
    'title' => 'Library One',
    'website' => 'http://tympanus.net/Development/Slicebox/',
    'version' => '1.0',
    'js' => array(
      drupal_get_path('module', 'juanrueda_libraries') . '/js/jquery.easing.1.3.js' => array(),
      drupal_get_path('module', 'juanrueda_libraries') . '/js/jquery.elastislide.js' => array(),
    ),
    'css' => array(
      drupal_get_path('module', 'juanrueda_libraries') . '/css/demo.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      drupal_get_path('module', 'juanrueda_libraries') . '/css/elastislide.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
      drupal_get_path('module', 'juanrueda_libraries') . '/css/reset.css' => array(
        'type' => 'file',
        'media' => 'screen',
      ),
    ),
  );

  return $libraries;
}
