<?php

/**
 * Implements hook_views_post_execute().
 */

function juanrueda_views_breadcrumb_views_post_execute(&$view) {

    if ($view->name == 'camiones') {
        $breadcrumb[] = l('Inicio', '<front>');
        $breadcrumb[] = l('Camiones', 'camiones');
        drupal_set_breadcrumb($breadcrumb);
    }if($view->name == "Noticias y Eventos"){
        $breadcrumb[] = l('Inicio', '<front>');
        $breadcrumb[] = l('Noticias y Eventos', 'noticias-y-eventos');
        drupal_set_breadcrumb($breadcrumb);
    }
}
