<?php

function juanrueda_response_init() {
  $path = drupal_get_path('module', 'juanrueda_response');
  drupal_add_js($path . '/juanrueda_response.js');

  $path_theme = drupal_get_path('theme', 'juan_rueda');
  dpm($_SERVER['HTTP_USER_AGENT']);

  if(strpos($_SERVER['HTTP_USER_AGENT'], 'MSIE 7') !== FALSE) {
     dpm('entro');
    drupal_add_js(array('ei7' => 1), 'setting');

    drupal_add_css($path_theme . '/css/ie7.css');
  }

 }

