<?php

define('RUTA_DEFECTO_THEME', drupal_get_path('theme', 'juan_rueda'));

function cargar_estilos_mobile($useragent) {

  $dm_usergent = array(
   'PIE4' => 'compatible; MSIE 4.01; Windows CE; PPC; 240x320',
   'PIE4_Smartphone' => 'compatible; MSIE 4.01; Windows CE; Smartphone;',
   'PIE6' => 'compatible; MSIE 6.0; Windows CE;',
   'Minimo' => 'Minimo',
   'OperaMini' => 'Minimo',
   'AvantGo' => 'AvantGo',
   'Plucker' => 'Plucker',
   'NetFront' => 'NetFront',
   'SonyEricsson' => 'SonyEricsson',
   'Nokia' => 'Nokia',
   'Motorola' => 'mot-',
   'BlackBerry' => 'BlackBerry',
   'WindowsMobile' => 'Windows CE',
   'PPC' => 'PPC',
   'PDA' => 'PDA',
   'Smartphone' => 'Smartphone',
   'Palm' => 'Palm'
);

if ($useragents) {
   foreach($useragents as $nav=>$ua){
      if(strstr($useragent, $ua)!=false){
        drupal_add_css(RUTA_DEFECTO_THEME . '/css/mobile.css');
      }
   }
 }
}



function juanrueda_response_init() {
  $path = drupal_get_path('module', 'juanrueda_response');
  drupal_add_js($path . '/juanrueda_response.js');

  cargar_estilos_mobile($_SERVER['HTTP_USER_AGENT']);

  drupal_add_css(RUTA_DEFECTO_THEME . '/css/ie7.css', array('group' => CSS_THEME, 'weight' => 1000));

 }


function juanrueda_response_css_alter(&$css) {
  if (preg_match('/MSIE [7]./', $_SERVER['HTTP_USER_AGENT'])) {

    $exclude = array(
      'sites/all/themes/omega/alpha/css/alpha-mobile.css' => FALSE,
      'sites/all/themes/juan_rueda/css/juan-rueda-alpha-default.css' => FALSE,
      'sites/all/themes/juan_rueda/css/juan-rueda-alpha-default-normal.css' => FALSE,
     // 'sites/all/themes/omega/alpha/css/grid/alpha_default/normal/alpha-default-normal-12.css' => FALSE,
      'sites/all/themes/juan_rueda/css/juan-rueda-alpha-default-narrow.css' => FALSE,
    //  'sites/all/themes/omega/alpha/css/grid/alpha_default/narrow/alpha-default-narrow-12.css' > FALSE,
      'sites/all/themes/juan_rueda/css/juan-rueda-alpha-default-wide.css' => FALSE,
    //  'sites/all/themes/omega/alpha/css/grid/alpha_default/wide/alpha-default-wide-12.css' => FALSE,

    );
    $css = array_diff_key($css, $exclude);

  }

}
